project/models.py
from flask_login import UserMixin
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()

class Users(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(100), unique=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))

    def __init__(self, username, email, password):
        self.username = username
        self.email = email
        self.password = password

@login_manager.user_loader
def load_user(user_id): 
    return Users.query.get(int(user_id))

    

project/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo

class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Log In')

project/__init__.py
from flask import Flask
from project.models import db, migrate, login_manager
from project.routes import auth


def create_app():
    app = Flask(__name__)
    app.config.from_object('config.BaseConfig')
    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)
    app.register_blueprint(auth)
    return app 

project/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash
from .forms import RegistrationForm, LoginForm
from .models import Users, db
from flask import Blueprint, jsonify, request
from flask_login import login_user, login_required, current_user, logout_user

auth = Blueprint('auth', __name__)


@auth.route('/alive', methods=['GET'])
def alive():
    return "Alive"

@auth.route('/')
@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = Users(username=form.username.data, email=form.email.data, password=form.password.data)
        print(new_user)
        db.session.add(new_user)
        db.session.commit()
        print("success")
        # Save new_user to the database
        flash('Account created successfully. You can now log in.', 'success')
        return redirect(url_for('auth.login'))
    return render_template('signup.html', form=form)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        # Check if the user exists and the password is correct
        user = Users.query.filter_by(email=form.email.data).first()
        if user and user.password == form.password.data:
            login_user(user)
            flash('Logged in successfully.', 'success')
            return redirect(url_for('auth.profile'))
        else:
            flash('Invalid email or password.', 'danger')
    return render_template('login.html', form=form)
       

@auth.route('/profile')
@login_required
def profile():
    # Get the user's profile information
    return render_template('profile.html', user=current_user)

@auth.route('/users', methods=['GET'])
@login_required
def get_users():
    users = Users.query.all()
    user_list = [{'id': user.id, 'username': user.username, 'email': user.email} for user in users]
    return render_template('users.html', user_list=user_list)

@auth.route('/logout')
def logout():
    logout_user()
    flash(f'You are currently logged out!', category='info')
    return redirect(url_for('auth.signup'))

project/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <title>Flask User Authentication</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>
<body>
  <nav class="navbar">
    <div class="container">
     
      <ul class="nav">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.signup') }}">Sign Up</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth.login') }}">Log In</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.profile') }}">Profile</a>
          </li>
        <li class="nav-item">
        <a class="nav-link" href="{{ url_for('auth.get_users') }}">Users</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
        </li>
      </ul>
    </div>
  </nav>

  <div class="content">
    {% block content %}{% endblock %}
  </div>

  
</body>
</html>

project/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h2 class="text-center">Log In</h2>
  <form method="POST" action="{{ url_for('auth.login') }}">
    {{ form.csrf_token }}
    <div class="form-group">
      {{ form.email.label }}
      {{ form.email(class="form-control") }}
      {% for error in form.email.errors %}
      <span class="text-danger">{{ error }}</span>
      {% endfor %}
    </div>
    <div class="form-group">
      {{ form.password.label }}
      {{ form.password(class="form-control") }}
      {% for error in form.password.errors %}
      <span class="text-danger">{{ error }}</span>
      {% endfor %}
    </div>
    <button type="submit" class="btn btn-primary">Log In</button>
  </form>
</div>
{% endblock %}

project/templates/profile.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h2 class="text-center">User Profile</h2>
  <div class="profile-info">
    <p><strong>Username:</strong> {{user.username}}</p>
    <p><strong>Email:</strong> {{user.email}}</p>
  </div>
</div>
{% endblock %}

project/templates/signup.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <h2 class="text-center">Sign Up</h2>
  <form method="POST" action="{{ url_for('auth.signup') }}">
    {{ form.csrf_token }}
    <div class="form-group">
      {{ form.username.label }}
      {{ form.username(class="form-control") }}
      {% for error in form.username.errors %}
      <span class="text-danger">{{ error }}</span>
      {% endfor %}
    </div>
    <div class="form-group">
      {{ form.email.label }}
      {{ form.email(class="form-control") }}
      {% for error in form.email.errors %}
      <span class="text-danger">{{ error }}</span>
      {% endfor %}
    </div>
    <div class="form-group">
      {{ form.password.label }}
      {{ form.password(class="form-control") }}
      {% for error in form.password.errors %}
      <span class="text-danger">{{ error }}</span>
      {% endfor %}
    </div>
    <div class="form-group">
      {{ form.confirm_password.label }}
      {{ form.confirm_password(class="form-control") }}
      {% for error in form.confirm_password.errors %}
      <span class="text-danger">{{ error }}</span>
      {% endfor %}
    </div>
    <button type="submit" class="btn btn-primary">Sign Up</button>
  </form>
</div>
{% endblock %}

project/templates/users.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h2 class="text-center">User Info</h2>
    
            <ul>
                {% for user in user_list %}
                <div class="user-info">
                    <li><p><strong>Username: </strong>{{ user.username}}<strong>Email: </strong>{{ user.email }}</p></li>
                </div>
                {% endfor %}
            </ul>
        
    </div>
{% endblock %}